apiVersion: apps/v1
kind: Deployment
metadata:
  name: sryfhdcgb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sryfhdcgb
  template:
    metadata:
      labels:
        app: sryfhdcgb
    spec:
      containers:
      - image: okteto.dev/sryfhdcgb:latest
        name: sryfhdcgb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7031560e-6228-45f4-9181-ef78d38d22b8"
        - name: Vless_Path
          value: "/vlgaud68hu5"
        - name: Vmess_UUID
          value: "7031560e-6228-45f4-9181-ef78d38d22b8"
        - name: Vmess_Path
          value: "/vm5cfhcgj565y"
        - name: Share_Path
          value: "/v2link"
